Online_Assigment_Submission/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('application/', include('Application.urls')),
    path('api/', include('api_app.urls')),
    path('ui_api/', include('ui_app.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ui_app/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *

urlpatterns = [
    path('', UserIndexView.as_view(), name='ui_home_page'),
    path('user/register/', UserRegisterView.as_view(), name='user_register'),
    path('login/user/', UserLoginView.as_view(), name='login_user'),
    path('logout/user/', UserLogoutView.as_view(), name='ui_logout'),
    path('user/home/page/', HomePageView.as_view(), name='user_home_page'),
    path('add/course/', AddCourseView.as_view(), name='add_course'),
    path('add/assignments/<int:id>/', AddAssignmentView.as_view(), name="add_assigment_view"),
    path('show/assignments/<int:id>/', ShowAssignment.as_view(), name='show_assigment_view'),
    path('stud/assignment/<int:id>/', StudAssignment.as_view(), name='stud_assigment_view'),
    path('show/courses/', ShowCourses.as_view(), name='show_courses'),
    path('assignment/details/<int:id>/', AssignmentDetails.as_view(), name="assignment_details"),
    path('add/solution/<int:id>/', AddSolution.as_view(), name='add_solution'),
    path('show/solution/<int:id>/', ShowSolution.as_view(), name='show_solution'),
    path('show/solutions/assignemnt/', Solution_Assignment.as_view(), name='solution_assignment'),

    path('edit/solution/<int:id>/', EditSolution.as_view(), name="edit_solution"),


    url(r'^login/user/(?P<data>.*)/$', UserLoginView.as_view(), name='login_user')
]

Application/models.py
from django.db import models
from django.contrib.auth.models import User


class Course(models.Model):
    Course = models.CharField(max_length=100,)

    class Meta:
        verbose_name_plural = "Courses"
    def __str__(self):
        return self.Course


class Assigment(models.Model):
    Name = models.CharField(max_length=100)
    Questions = models.TextField()
    Year = models.CharField(max_length=100)
    Created_date = models.DateTimeField(auto_now_add=True)
    Deadline = models.DateTimeField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.Name

    # def get_solution(self):
    #     try:
    #         return Solution.objects.get(ass=self)
    #     except Solution.DoesNotExist:
    #         return None


class Solution(models.Model):
    ass = models.ForeignKey(Assigment, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    answer = models.TextField()
    files = models.FileField(upload_to="Documents/", null=True, blank=True)
    points = models.FloatField(null=True, default=0.0)
    comments = models.CharField(max_length=300, null=True)
    created_date = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.ass.Name}"

ui_app/models.py
from django.db import models

# Create your models here.

Application/forms.py
from django import forms
from . import models
from .validators import validate_email, validate_course


class UserModelForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(validators=[validate_email])

    class Meta:
        model = models.User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


class LoginForm(forms.Form):
    Username = forms.CharField(max_length=150)
    Password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ['Username', 'Password']


class CourseModelForm(forms.ModelForm):
    Course = forms.CharField(validators=[validate_course])

    class Meta:
        model = models.Course
        fields = ['Course']


class AssigmentModelForm(forms.ModelForm):
    Deadline = forms.CharField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = models.Assigment
        fields = ['Name', 'Questions', 'Deadline']


class SolutionModelForm(forms.ModelForm):

    class Meta:
        model = models.Solution
        fields = ['title', 'answer', 'files']


class PointsCommentsModelForm(forms.ModelForm):
    class Meta:
        model = models.Solution
        fields = ['answer', 'points', 'comments']

ui_app/forms.py
from Application.forms import *

ui_app/views.py
import requests
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import View
from Application.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout


class UserIndexView(View):
    template_name = 'ui_base.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)


class UserRegisterView(View):
    template_name = 'user_registration.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        context_data = {}
        response = requests.request(
            method="post",
            url='http://127.0.0.1:8000/' + 'api/registration/',
            data=self.request.POST

        ).json()
        context_data.update({
            'data': response
        })
        if 'status' in response:
            if response['status'] == 201:
                return HttpResponseRedirect(reverse_lazy('login_user', kwargs={
                    'data': 'Registration Successful, Kindly check your mail and confirm your account.'}))
        else:
            return render(self.request, self.template_name, context_data)


class UserLoginView(View):
    template_name = 'login_user.html'

    def get(self, *args, **kwargs):
        if 'data' in self.kwargs:
            context_data = {
                'data': self.kwargs['data']
            }
            return render(self.request, self.template_name, context_data)
        else:
            return render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        response = requests.request(
            method="post",
            url='http://127.0.0.1:8000/' + 'api/login/',
            data=self.request.POST
        ).json()
        if 'message' in response:
            context_data = {
                'data': response['message']
            }
            return render(self.request, self.template_name, context_data)
        else:
            if response.get('login_teacher', None):
                username = response['login_teacher']
                user = User.objects.get(username=username)
                login(self.request, user)
                self.request.session['teacher'] = response['login_teacher']
                return HttpResponseRedirect(reverse_lazy('user_home_page'))
            elif response.get('login_student', None):
                username = response['login_student']
                user = User.objects.get(username=username)
                login(self.request, user)
                self.request.session['student'] = response['login_student']
                return HttpResponseRedirect(reverse_lazy('show_courses'))


class UserLogoutView(View):

    def get(self, *args, **kwargs):
        response = requests.request(
            method="get",
            url='http://127.0.0.1:8000/' + 'api/logout/',
            data=self.request.GET
        ).json()
        try:
            logout(self.request)
            del self.request.session['teacher']
            del self.request.session['student']
            return HttpResponseRedirect(reverse_lazy('login_user'))
        except KeyError:
            return HttpResponseRedirect(reverse_lazy('login_user'))


class HomePageView(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = 'home_page_view.html'

    def get(self, *args, **kwargs):
        context_data = {}
        response = requests.request(
            method="get",
            url='http://127.0.0.1:8000/' + 'api/add/course/',
            data=self.request.GET

        ).json()
        context_data.update({
            "data": response
        })
        return render(self.request, self.template_name, context_data)


class AddCourseView(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = 'add_courses.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        context_data = {}
        context_data.update(
            response=requests.request(
                method="post",
                url='http://127.0.0.1:8000/' + 'api/add/course/',
                data=self.request.POST

            ).json()
        )
        return HttpResponseRedirect(reverse_lazy('user_home_page'))


class AddAssignmentView(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = "add_assignment.html"

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        response = requests.request(
            method="post",
            url=f'http://127.0.0.1:8000/api/add/assignment/{kwargs.get("id")}/',
            data=self.request.POST

        ).json()
        print(self.request.POST)
        print(response)
        return HttpResponseRedirect(reverse_lazy('user_home_page'))


class ShowAssignment(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = "show_assignment.html"

    def get(self, *args, **kwargs):
        context_data = {}
        response = requests.request(
            method="get",
            url=f'http://127.0.0.1:8000/api/add/assignment/{kwargs.get("id")}/',
            data=self.request.GET
        ).json()
        context_data.update({
            "data": response
        })
        return render(self.request, self.template_name, context_data)


class StudAssignment(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = "stud_assign.html"

    def get(self, *args, **kwargs):
        context_data = {}
        response = requests.request(
            method="get",
            url=f'http://127.0.0.1:8000/api/add/assignment/{kwargs.get("id")}/',
            data=self.request.GET
        ).json()
        context_data.update({
            "assignment": response
        })
        return render(self.request, self.template_name, context_data)


class ShowCourses(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = "student_home_view.html"

    def get(self, *args, **kwargs):
        context_data = {}
        response = requests.request(
            method="get",
            url=f'http://127.0.0.1:8000/api/show/courses/',
            data=self.request.GET
        ).json()
        context_data.update({
            "data": response
        })
        return render(self.request, self.template_name, context_data)


class AddSolution(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = "add_solution.html"

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        response = requests.request(
            method="post",
            url=f'http://127.0.0.1:8000/api/add/solution/{kwargs.get("id")}/',
            data={
                'title': self.request.POST['title'],
                'answer': self.request.POST['answer'],
                'file': self.request.FILES['files'],
                'user': self.request.session['student']
            },
            headers={'Content-Type': 'application/x-www-form-urlencoded',
                     'Content-Disposition': 'attachment; filename="file"'}
        ).json()
        print(response)
        return HttpResponseRedirect(reverse_lazy('solution_assignment'))


class EditSolution(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = 'edit_solution.html'

    def get(self, *args, **kwargs):
        context_data = {}
        response = requests.request(
            method="get",
            url=f'http://127.0.0.1:8000/api/edit/solution/{kwargs.get("id")}/',
            data=self.request.GET
        ).json()
        print(response)
        context_data.update({
            'data': response
        })
        return render(self.request, self.template_name, context_data)

    def post(self, *args, **kwargs):
        response = requests.request(
            method="post",
            url=f'http://127.0.0.1:8000/api/edit/solution/{kwargs.get("id")}/',
            data=self.request.POST
        ).json()
        return HttpResponseRedirect(reverse_lazy('solution_assignment'))


class ShowSolution(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = "show_Solution.html"

    def get(self, *args, **kwargs):
        context_data = {}
        assign = Assigment.objects.get(id=self.kwargs['id'])
        response = requests.request(
            method="get",
            url=f'http://127.0.0.1:8000/api/show/solution/{kwargs.get("id")}/',
            data=self.request.GET
        ).json()
        context_data.update({
            "data": response,
            "assign": assign
        })
        return render(self.request, self.template_name, context_data)


class AssignmentDetails(LoginRequiredMixin, View):
    login_url = 'login_user'
    template_name = "assignment_details.html"

    def get(self, *args, **kwargs):
        username = self.request.session['student']
        user = User.objects.get(username=username)
        assign = Assigment.objects.get(id=self.kwargs["id"])
        try:
            if Solution.objects.get(ass=assign, user=user):
                return HttpResponseRedirect(reverse_lazy('solution_assignment'))
        except Solution.DoesNotExist:
            context_data = {}
            response = requests.request(
                method="get",
                url=f'http://127.0.0.1:8000/api/assignment/details/{kwargs.get("id")}/',
                data={
                    'data': self.request.GET,
                    'user': self.request.session['student']
                }
            ).json()
            context_data.update({
                "data": response
            })
            return render(self.request, self.template_name, context_data)


class Solution_Assignment(LoginRequiredMixin, View):

ui_app/templates/add_assignment.html
{% extends 'ui_base.html' %}


{% block content %}

    <form method="post">
        {% csrf_token %}
        <h1>Add an Assigment</h1>
        <hr>
        <table>
            <tbody>
                <tr>
                    <th><label for="id_Name">Name:</label></th>
                    <td><input type="text" name="Name" value="" maxlength="100" required="" id="id_Name"></td>
                </tr>
                <tr>
                    <th><label for="id_Questions">Questions:</label></th>
                    <td><textarea name="Questions"  cols="40" rows="10" required="" id="id_Questions"></textarea></td>
                </tr>
                <tr>
                    <th><label for="id_Deadline">Deadline:</label></th>
                    <td><input type="datetime-local" name="Deadline" value="" required="" id="id_Deadline"></td>
                </tr>
            </tbody>
        </table>
        <input type="submit" value="Add" class="btn btn-lg btn-success">
    </form>

{% endblock %}

ui_app/templates/add_courses.html
{% extends 'ui_base.html' %}


{% block title %} Add Course{% endblock %}
{% block content %}

<form action="{% url 'add_course' %}" method="post">
    {% csrf_token %}
    <table>
        <tbody>
            <tr>
                <th><label for="id_Course">Course:</label></th>
                <td><input type="text" name="Course" value="" required="" id="id_Course"></td>
            </tr>
        </tbody>
    </table>
    <input type="submit" value="ADD" class="btn btn-success">
</form>

{% endblock %}

ui_app/templates/add_solution.html
{% extends 'ui_base.html' %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Submit a Solution</h1>
        <table>
            <tbody>
                <tr>
                    <th><label for="id_title">Title:</label></th>
                    <td><input type="text" name="title" maxlength="100" required="" id="id_title"></td>
                </tr>
                <tr>
                    <th><label for="id_answer">Answer:</label></th>
                    <td><textarea name="answer" cols="40" rows="10" required="" id="id_answer"></textarea></td>
                </tr>
                 <tr>
                    <th><label for="id_files">Files:</label></th>
                    <td><input type="file" name="files" required="" id="id_files"></td>
                </tr>
            </tbody>
        </table>
    <input type="submit" VALUE="submit" class="btn btn-lg btn-success">
    </form>

{% endblock %}

ui_app/templates/assignment_details.html
{% extends 'ui_base.html' %}

{% block content %}

    <h1>{{ data.Name }}</h1>
    <br>
    <h3>Deadline : {{ data.Deadline }}</h3>
    <hr>
    <h3>Question:
    {{ data.Questions }}</h3>
    <hr>
    <a href="{% url 'add_solution' data.id %}"><input type="submit" value="Add Solution" class="btn btn-lg btn-info"></a>

{% endblock %}

ui_app/templates/edit_solution.html
{% extends 'ui_base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <h1>Edit a Solution</h1>
        <table>
            <tbody>
                <tr>
                    <th><label for="id_title">Title:</label></th>
                    <td><input type="text" name="title" value="{{ data.title }}" maxlength="100" required="" id="id_title"></td>
                </tr>
                <tr>
                    <th><label for="id_answer">Answer:</label></th>
                    <td><textarea name="answer" cols="40" rows="10" required="" id="id_answer">{{ data.answer }}</textarea></td>
                </tr>
            </tbody>
        </table>

    <input type="submit" VALUE="submit" class="btn btn-lg btn-success">
    </form>

{% endblock %}

ui_app/templates/home_page_view.html
{% extends 'ui_base.html' %}

{% block content %}

<h1>Subjects List</h1>
<hr>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Courses</th>
          <th scope="col">Add Assignments</th>
        </tr>
      </thead>
      <tbody>
      {% for i in data %}
        <tr>
            <td><a href="{% url 'show_assigment_view' i.id %}" class="btn btn-block btn-primary">{{ i.Course }}</a></td>
            <td><a href="{% url 'add_assigment_view' i.id %}" class="btn btn-block btn-success"> Add Assignment</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

{% endblock %}

ui_app/templates/login_user.html
{% extends 'ui_base.html' %}


{% block css %}
    <style>
        tr, td ,th{
            margin: 20%;
            padding: 5px;

        }
        input[type=text], input[type=password], input[type=email]{
          width: 400%;
          padding: 15px;
          margin: 5px 0 22px 0;
          display: inline-block;
          border: none;
          background: #f1f1f1;
        }
        input[type=submit]{
            height: 50px;
            width: 70%;
            font-size: 20px ;
            font-weight: bold;
            margin-left: 15%;
        }
    </style>
 {% endblock %}
{% block title %} User Login {% endblock %}
{% block content %}

<form action="{% url 'login_user' %}" method="post">

    <h4 style="color: green">
        {{ data }}
    </h4>

    {% csrf_token %}
    <table>
        <tbody>
        <tr>
            <th><label for="id_Username">Username:</label></th>
            <td><input type="text" name="Username" value="" maxlength="150" required="" id="id_Username"></td>
        </tr>
        <tr>
            <th><label for="id_Password">Password:</label></th>
            <td><input type="password" name="Password" value="" required="" id="id_Password"></td>
        </tr>
        </tbody>
    </table>
    <input type="submit" value="Login" class="btn btn-lg btn-success">
</form>

{% endblock %}

ui_app/templates/show_Solution.html
{% extends 'ui_base.html' %}

{% block content %}

    <h1>{{ assign }}</h1>
    <br>
    <h3>Deadline : {{ assign.Deadline }}</h3>
    <hr>
    <h3>Question:
    {{ assign.Questions }}</h3>
    <hr>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Submission Date</th>
          <th scope="col">Author</th>
        </tr>
      </thead>
      <tbody>
         {% for i in data %}
        <tr>
            <td>{{ i.title }}</td>
            <td>{{ i.created_date }}</td>
            <td>{{ i.user }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

{% endblock %}

ui_app/templates/show_assignment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Document</title>
     {% block css %}
         <style>
        tr, td ,th{
            margin: 20%;
            padding: 5px;
            all-space-treatment: 20%;
        }
        body {
          font-family: Arial, Helvetica, sans-serif;

        }
        * {
          box-sizing: border-box;
        }
        .container {
          padding: 16px;
          background-color: white;
        }
        input[type=text], input[type=password], input[type=date], input[type=email], input[type=number],textarea{
          width: 200%;
          padding: 15px;
          margin: 5px 0 22px 0;
          display: inline-block;
          border: none;
          background: #f1f1f1;
        }
        input[type=submit]{
            height: 50px;
            width: 70%;
            font-size: 20px ;
            font-weight: bold;
            margin-left: 15%;
        }
        input[type=text]:focus, input[type=password]:focus {
          background-color: #ddd;
          outline: none;
        }

        /* Overwrite default styles of hr */
        hr {
          border: 1px solid #f1f1f1;
          margin-bottom: 25px;
        }
        a {
          color: dodgerblue;
        }
    </style>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Online Assigment Submission</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if request.session.teacher %}
        <li><a href="{% url 'ui_logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout </a></li>
      {% else %}
        <li><a href="{% url 'user_register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up </a></li>
        <li><a href="{% url 'login_user' %}"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="container">

  <div class="panel panel-default" >
    <div class="panel-body" style="alignment: center">


{% block content %}

    <h2>{% block title %} {{ request.session.teacher }}'s Assigment {% endblock %}</h2>
    <hr>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Assignment's Name</th>
          <th scope="col">Deadline</th>
        </tr>
      </thead>
      <tbody>
      {% for i in data %}
        <tr>
            <td><a href="{% url 'show_solution' i.id %}">{{ i.Name }}</a></td>
            <td>{{ i.Deadline }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>


{% endblock %}

    </div>
  </div>
</div>

</body>
</html>

ui_app/templates/solution_assignment.html
{% extends 'ui_base.html' %}

{% block content %}

    <h1> {{ request.session.student }}'s Assigment</h1>
    <hr>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Assignment's Name</th>
          <th scope="col">Deadline</th>
          <th scope="col">Solution</th>
          <th scope="col">Points</th>
          <th scope="col">Comments</th>
        </tr>
      </thead>
      <tbody>
      {% for solution in data %}
        <tr>
            <td><a href="{% url 'edit_solution' solution.id %}">{{ solution.ass }}</a></td>
            <td>{{ solution.deadline }}</td>
            <td>{{ solution.title }}</td>
            <td>{{ solution.points }}</td>
            <td>{{ solution.comments }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>


{% endblock %}

ui_app/templates/stud_assign.html
{% extends 'ui_base.html' %}

{% block content %}

 <h1> {{ request.session.student }}'s Assigment</h1>
    <hr>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Assignment's Name</th>
          <th scope="col">Deadline</th>
        </tr>
      </thead>
      <tbody>
          {% for i in assignment %}
            <tr>
                <td><a href="{% url 'assignment_details' i.id %}">{{ i.Name }}</a></td>
                <td>{{ i.Deadline }}</td>
            </tr>
          {% endfor %}
      </tbody>
    </table>

{% endblock %}

ui_app/templates/student_home_view.html
{% extends 'ui_base.html' %}

{% block content %}

<h1> Subjects List </h1>
<hr>
{% for i in data %}
    <a href="{% url 'stud_assigment_view' i.id %}" class="btn btn-block btn-primary">{{i.Course}}</a>
{% endfor %}

{% endblock %}

ui_app/templates/user_registration.html
{% extends 'ui_base.html' %}



{% block title %} User Registration {% endblock %}
{% block content %}

    <h4 style="color: red">
        {% for key, value in data.items %}
            {{ key }} : {{ value.0 }} <br>
        {% endfor %}
    </h4>

<form action="{% url 'user_register' %}" method="post">
    {% csrf_token %}
    <table>
        <tbody>
            <tr>
                <th>
                    <label for="id_username">Username:</label>
                </th>
                <td>
                    <input type="text" name="username" value="" maxlength="150" required="" id="id_username">
                    <br><span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_first_name">First name:</label>
                </th>
                <td>
                    <input type="text" name="first_name" value="" maxlength="150" id="id_first_name">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_last_name">Last name:</label>
                </th>
                <td>
                    <input type="text" name="last_name" value="" maxlength="150" id="id_last_name">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_email">Email:</label>
                </th>
                <td>
                    <input type="email" name="email" value="" required="" id="id_email">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_password">Password:</label>
                </th>
                <td>
                    <input type="password" name="password" value="" required="" id="id_password">
                </td>
            </tr>
        </tbody>
    </table>
    <input type="submit" value="Submit" class="btn btn-lg btn-success">
</form>

{% endblock %}